# **CLIMATE DATA**

In [2]:
import pandas as pd

In [3]:
climate_data_2024 = pd.read_csv(r"C:\Users\sofia\Documents\Data_Analytics_Ironhack\Projects\google_brain\Climate_data\INMET_CO_DF_A001_BRASILIA_01-01-2024_A_31-12-2024.csv",
                                skiprows=8,
                                sep=";",         
                                encoding="latin1")

climate_data_2024.head()

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
0,2024/01/01,0000 UTC,0,"885,7","885,7","885,3",NaN,22,"18,2","22,6","21,8","18,6","18,2",81.0,77.0,79.0,311.0,"2,8","1,5",NaN
1,2024/01/01,0100 UTC,0,"886,7","886,7","885,7",NaN,"21,2","18,6",22,"21,1","18,7","18,1",85.0,79.0,85.0,315.0,"2,9","1,5",NaN
2,2024/01/01,0200 UTC,0,"887,1","887,2","886,7",NaN,"20,9","18,8","21,5","20,9","18,9","18,7",88.0,85.0,88.0,305.0,"3,3","1,1",NaN
3,2024/01/01,0300 UTC,0,"887,1","887,4","887,1",NaN,"20,9","18,3","21,1","20,8","18,9","18,3",88.0,85.0,85.0,304.0,"3,3","1,5",NaN
4,2024/01/01,0400 UTC,0,"886,4","887,1","886,4",NaN,"20,5","18,6",21,"20,5","18,6","18,3",89.0,85.0,89.0,315.0,4,2,NaN

In [4]:
climate_data_2024.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 20 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   Data                                                   8784 non-null   object
 1   Hora UTC                                               8784 non-null   object
 2   PRECIPITAÇÃO TOTAL, HORÁRIO (mm)                       8760 non-null   object
 3   PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)  8760 non-null   object
 4   PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)        8760 non-null   object
 5   PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)       8760 non-null   object
 6   RADIACAO GLOBAL (Kj/m²)                                4704 non-null   object
 7   TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)           8758 non-null   object
 8   TEMPERATURA DO PONTO DE ORVALHO (°C)                   8758 non-null   object
 9   TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)             8758 non-null   object
 10  TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)             8758 non-null   object
 11  TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)       8758 non-null   object
 12  TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)       8758 non-null   object
 13  UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)               8758 non-null   float64
 14  UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)               8757 non-null   float64
 15  UMIDADE RELATIVA DO AR, HORARIA (%)                    8758 non-null   float64
 16  VENTO, DIREÇÃO HORARIA (gr) (° (gr))                   8758 non-null   float64
 17  VENTO, RAJADA MAXIMA (m/s)                             8760 non-null   object
 18  VENTO, VELOCIDADE HORARIA (m/s)                        8759 non-null   object
 19  Unnamed: 19                                            0 non-null      float64
dtypes: float64(5), object(15)
memory usage: 1.3+ MB

In [5]:
climate_data_2024['Data'] = pd.to_datetime(climate_data_2024['Data'], format="%Y/%m/%d", errors='coerce')

for col in climate_data_2024.columns[2:]: #starting on the third column
    climate_data_2024[col] = (
        climate_data_2024[col].astype(str)
        .str.replace(",", ".")
        .str.strip()
        .replace("", "0")
        .astype(float)
    )

meteo_daily_2024 = climate_data_2024.groupby('Data').agg({
    'PRECIPITAÇÃO TOTAL, HORÁRIO (mm)': 'sum',
    'RADIACAO GLOBAL (Kj/m²)': 'mean',
    'TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)': 'mean',
    'TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)': 'max',
    'TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)': 'min',
    'TEMPERATURA DO PONTO DE ORVALHO (°C)': 'mean',
    'UMIDADE RELATIVA DO AR, HORARIA (%)': 'mean',
    'VENTO, RAJADA MAXIMA (m/s)': 'max',
    'VENTO, VELOCIDADE HORARIA (m/s)': 'mean'
}).reset_index()


meteo_daily_2024.rename(columns={
    'PRECIPITAÇÃO TOTAL, HORÁRIO (mm)': 'precipitacao_mm',
    'RADIACAO GLOBAL (Kj/m²)': 'radiacao_media',
    'TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)': 'temp_media',
    'TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)': 'temp_max',
    'TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)': 'temp_min',
    'TEMPERATURA DO PONTO DE ORVALHO (°C)': 'temp_orvalho_media',
    'UMIDADE RELATIVA DO AR, HORARIA (%)': 'humidade_media',
    'VENTO, RAJADA MAXIMA (m/s)': 'vento_rajada_max',
    'VENTO, VELOCIDADE HORARIA (m/s)': 'vento_vel_media'
}, inplace=True)

meteo_daily_2024.head()

,Data,precipitacao_mm,radiacao_media,temp_media,temp_max,temp_min,temp_orvalho_media,humidade_media,vento_rajada_max,vento_vel_media
0,2024-01-01,35.6,1094.385714,21.995833,26.7,19.4,18.666667,82.541667,6.2,1.658333
1,2024-01-02,23.2,1171.950000,21.187500,26.6,19.3,19.570833,91.000000,6.7,1.787500
2,2024-01-03,48.8,724.321429,20.537500,23.4,19.1,19.370833,93.375000,8.2,2.250000
3,2024-01-04,7.6,590.893333,20.375000,23.3,19.3,19.491667,94.750000,8.4,2.529167
4,2024-01-05,2.4,833.607143,20.400000,23.2,18.9,19.004167,92.125000,11.1,2.545833

In [6]:
meteo_daily_2024.shape

(366, 10)

In [7]:
meteo_daily_2024.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Data                366 non-null    datetime64[ns]
 1   precipitacao_mm     366 non-null    float64
 2   radiacao_media      366 non-null    float64
 3   temp_media          366 non-null    float64
 4   temp_max            366 non-null    float64
 5   temp_min            366 non-null    float64
 6   temp_orvalho_media  366 non-null    float64
 7   humidade_media      366 non-null    float64
 8   vento_rajada_max    366 non-null    float64
 9   vento_vel_media     366 non-null    float64
dtypes: datetime64[ns](1), float64(9)
memory usage: 28.7 KB

In [8]:
climate_data_2023 = pd.read_csv(r"C:\Users\sofia\Documents\Data_Analytics_Ironhack\Projects\google_brain\Climate_data\INMET_CO_DF_A001_BRASILIA_01-01-2023_A_31-12-2023.csv",
                                skiprows=8,
                                sep=";",         
                                encoding="latin1")

climate_data_2023.head()

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
0,2023/01/01,0000 UTC,0,"887,7","887,7","887,2",NaN,"20,1","17,9","20,9",20,"19,2","17,8",91.0,87.0,87.0,187.0,"3,3","1,2",NaN
1,2023/01/01,0100 UTC,0,"888,1","888,1","887,7",NaN,"19,2","17,5","20,1","19,2","17,8","17,4",90.0,87.0,90.0,153.0,"2,9",",8",NaN
2,2023/01/01,0200 UTC,0,"887,8","888,1","887,8",NaN,"19,3","17,6","19,5",19,"17,8","17,3",90.0,89.0,90.0,145.0,"2,5","1,5",NaN
3,2023/01/01,0300 UTC,0,"887,8","887,9","887,7",NaN,"19,3","17,7","19,4","19,1","17,8","17,5",91.0,90.0,91.0,162.0,"3,2","1,4",NaN
4,2023/01/01,0400 UTC,0,"887,6","887,9","887,6",NaN,"19,7","18,1","19,7","19,1","18,1","17,4",91.0,90.0,90.0,140.0,"5,7","2,7",NaN

In [9]:
climate_data_2023['Data'] = pd.to_datetime(climate_data_2023['Data'], format="%Y/%m/%d", errors='coerce')

for col in climate_data_2023.columns[2:]: #starting on the third column
    climate_data_2023[col] = (
        climate_data_2023[col].astype(str)
        .str.replace(",", ".")
        .str.strip()
        .replace("", "0")
        .astype(float)
    )

meteo_daily_2023 = climate_data_2023.groupby('Data').agg({
    'PRECIPITAÇÃO TOTAL, HORÁRIO (mm)': 'sum',
    'RADIACAO GLOBAL (Kj/m²)': 'mean',
    'TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)': 'mean',
    'TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)': 'max',
    'TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)': 'min',
    'TEMPERATURA DO PONTO DE ORVALHO (°C)': 'mean',
    'UMIDADE RELATIVA DO AR, HORARIA (%)': 'mean',
    'VENTO, RAJADA MAXIMA (m/s)': 'max',
    'VENTO, VELOCIDADE HORARIA (m/s)': 'mean'
}).reset_index()


meteo_daily_2023.rename(columns={
    'PRECIPITAÇÃO TOTAL, HORÁRIO (mm)': 'precipitacao_mm',
    'RADIACAO GLOBAL (Kj/m²)': 'radiacao_media',
    'TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)': 'temp_media',
    'TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)': 'temp_max',
    'TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)': 'temp_min',
    'TEMPERATURA DO PONTO DE ORVALHO (°C)': 'temp_orvalho_media',
    'UMIDADE RELATIVA DO AR, HORARIA (%)': 'humidade_media',
    'VENTO, RAJADA MAXIMA (m/s)': 'vento_rajada_max',
    'VENTO, VELOCIDADE HORARIA (m/s)': 'vento_vel_media'
}, inplace=True)

meteo_daily_2023.head()

,Data,precipitacao_mm,radiacao_media,temp_media,temp_max,temp_min,temp_orvalho_media,humidade_media,vento_rajada_max,vento_vel_media
0,2023-01-01,0.2,1706.900000,21.895833,27.8,18.0,17.245833,76.791667,8.1,2.037500
1,2023-01-02,15.8,1654.521429,23.041667,28.2,19.6,16.508333,67.958333,9.0,2.558333
2,2023-01-03,0.4,1207.546154,20.812500,27.9,18.0,17.158333,81.000000,9.3,1.666667
3,2023-01-04,1.2,1402.992857,20.708333,26.0,17.7,17.170833,81.250000,9.2,2.512500
4,2023-01-05,0.8,1356.546154,21.162500,25.9,18.8,17.387500,79.875000,9.8,2.537500

In [10]:
climate_data_2022 = pd.read_csv(r"C:\Users\sofia\Documents\Data_Analytics_Ironhack\Projects\google_brain\Climate_data\INMET_CO_DF_A001_BRASILIA_01-01-2022_A_31-12-2022.csv",
                                skiprows=8,
                                sep=";",         
                                encoding="latin1")

climate_data_2022.head()

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
0,2022/01/01,0000 UTC,0,884,884,"882,9",NaN,"19,2","17,4","19,2",19,"17,4","17,2",90,89,89,356.0,"4,4","1,9",NaN
1,2022/01/01,0100 UTC,",4","884,4","884,4",884,NaN,19,"17,7","19,5",19,"17,7","17,4",92,88,92,350.0,"5,2","2,1",NaN
2,2022/01/01,0200 UTC,0,"884,2","884,4","884,2",NaN,"19,1","17,6","19,1","18,8","17,7","17,6",93,91,91,6.0,"5,1","2,6",NaN
3,2022/01/01,0300 UTC,0,884,"884,2",884,NaN,"18,8","17,2","19,2","18,8","17,6","17,2",91,89,91,2.0,"5,8","2,8",NaN
4,2022/01/01,0400 UTC,0,"883,2",884,"883,2",NaN,"18,5","17,2","18,8","18,4","17,3","17,1",92,91,92,11.0,"4,3","1,3",NaN

In [11]:
climate_data_2022['Data'] = pd.to_datetime(climate_data_2022['Data'], format="%Y/%m/%d", errors='coerce')

for col in climate_data_2022.columns[2:]: #starting on the third column
    climate_data_2022[col] = (
        climate_data_2022[col].astype(str)
        .str.replace(",", ".")
        .str.strip()
        .replace("", "0")
        .astype(float)
    )

meteo_daily_2022 = climate_data_2022.groupby('Data').agg({
    'PRECIPITAÇÃO TOTAL, HORÁRIO (mm)': 'sum',
    'RADIACAO GLOBAL (Kj/m²)': 'mean',
    'TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)': 'mean',
    'TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)': 'max',
    'TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)': 'min',
    'TEMPERATURA DO PONTO DE ORVALHO (°C)': 'mean',
    'UMIDADE RELATIVA DO AR, HORARIA (%)': 'mean',
    'VENTO, RAJADA MAXIMA (m/s)': 'max',
    'VENTO, VELOCIDADE HORARIA (m/s)': 'mean'
}).reset_index()


meteo_daily_2022.rename(columns={
    'PRECIPITAÇÃO TOTAL, HORÁRIO (mm)': 'precipitacao_mm',
    'RADIACAO GLOBAL (Kj/m²)': 'radiacao_media',
    'TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)': 'temp_media',
    'TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)': 'temp_max',
    'TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)': 'temp_min',
    'TEMPERATURA DO PONTO DE ORVALHO (°C)': 'temp_orvalho_media',
    'UMIDADE RELATIVA DO AR, HORARIA (%)': 'humidade_media',
    'VENTO, RAJADA MAXIMA (m/s)': 'vento_rajada_max',
    'VENTO, VELOCIDADE HORARIA (m/s)': 'vento_vel_media'
}, inplace=True)

meteo_daily_2022.head()

,Data,precipitacao_mm,radiacao_media,temp_media,temp_max,temp_min,temp_orvalho_media,humidade_media,vento_rajada_max,vento_vel_media
0,2022-01-01,25.8,691.728571,19.325000,22.9,18.2,17.850000,91.333333,10.0,3.120833
1,2022-01-02,3.8,1144.528571,19.975000,25.2,17.9,17.866667,88.250000,9.2,3.016667
2,2022-01-03,12.2,1474.742857,21.166667,27.3,18.4,17.916667,82.750000,8.8,2.287500
3,2022-01-04,3.2,1367.914286,20.916667,25.3,18.2,18.054167,84.416667,9.6,2.629167
4,2022-01-05,0.0,1886.385714,22.141667,28.4,17.3,17.229167,76.208333,8.6,2.666667

In [12]:
climate_data_2021 = pd.read_csv(r"C:\Users\sofia\Documents\Data_Analytics_Ironhack\Projects\google_brain\Climate_data\INMET_CO_DF_A001_BRASILIA_01-01-2021_A_31-12-2021.csv",
                                skiprows=8,
                                sep=";",         
                                encoding="latin1")

climate_data_2021.head()

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
0,2021/01/01,0000 UTC,0,"887,1","887,1","886,3",NaN,"20,9","15,9","22,4","20,8","16,5","15,4",75.0,67.0,73.0,327.0,"3,6",",8",NaN
1,2021/01/01,0100 UTC,0,"887,3","887,5","887,1",NaN,"20,5","16,4","21,1","19,5","16,9",16,83.0,73.0,78.0,134.0,"2,3","1,5",NaN
2,2021/01/01,0200 UTC,0,"887,9",888,"887,2",NaN,"19,6","16,1","21,4","19,6","16,5","15,9",80.0,73.0,80.0,309.0,"2,5","1,1",NaN
3,2021/01/01,0300 UTC,0,"887,6",888,"887,6",NaN,"19,4","16,7","20,1","19,3",17,"16,1",86.0,78.0,84.0,315.0,"2,3",",6",NaN
4,2021/01/01,0400 UTC,0,887,"887,6",887,NaN,"18,7","16,3","19,4","18,6","16,8",16,86.0,83.0,86.0,270.0,"1,4",",7",NaN

In [13]:
climate_data_2021['Data'] = pd.to_datetime(climate_data_2021['Data'], format="%Y/%m/%d", errors='coerce')

for col in climate_data_2021.columns[2:]: #starting on the third column
    climate_data_2021[col] = (
        climate_data_2021[col].astype(str)
        .str.replace(",", ".")
        .str.strip()
        .replace("", "0")
        .astype(float)
    )

meteo_daily_2021 = climate_data_2021.groupby('Data').agg({
    'PRECIPITAÇÃO TOTAL, HORÁRIO (mm)': 'sum',
    'RADIACAO GLOBAL (Kj/m²)': 'mean',
    'TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)': 'mean',
    'TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)': 'max',
    'TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)': 'min',
    'TEMPERATURA DO PONTO DE ORVALHO (°C)': 'mean',
    'UMIDADE RELATIVA DO AR, HORARIA (%)': 'mean',
    'VENTO, RAJADA MAXIMA (m/s)': 'max',
    'VENTO, VELOCIDADE HORARIA (m/s)': 'mean'
}).reset_index()


meteo_daily_2021.rename(columns={
    'PRECIPITAÇÃO TOTAL, HORÁRIO (mm)': 'precipitacao_mm',
    'RADIACAO GLOBAL (Kj/m²)': 'radiacao_media',
    'TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)': 'temp_media',
    'TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)': 'temp_max',
    'TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)': 'temp_min',
    'TEMPERATURA DO PONTO DE ORVALHO (°C)': 'temp_orvalho_media',
    'UMIDADE RELATIVA DO AR, HORARIA (%)': 'humidade_media',
    'VENTO, RAJADA MAXIMA (m/s)': 'vento_rajada_max',
    'VENTO, VELOCIDADE HORARIA (m/s)': 'vento_vel_media'
}, inplace=True)

meteo_daily_2021.head()

,Data,precipitacao_mm,radiacao_media,temp_media,temp_max,temp_min,temp_orvalho_media,humidade_media,vento_rajada_max,vento_vel_media
0,2021-01-01,1.4,1604.984615,22.133333,30.0,17.9,15.908333,69.500000,10.6,1.650000
1,2021-01-02,4.6,1562.076923,21.154167,29.1,17.5,15.616667,72.166667,11.5,2.033333
2,2021-01-03,33.8,1685.223077,21.829167,29.3,17.8,17.329167,78.458333,10.0,2.300000
3,2021-01-04,11.6,1042.638462,20.100000,25.2,17.8,16.745833,81.916667,9.0,2.420833
4,2021-01-05,0.2,1877.592308,22.050000,28.6,16.1,16.520833,74.291667,6.2,1.529167

In [14]:
climate_data_2020 = pd.read_csv(r"C:\Users\sofia\Documents\Data_Analytics_Ironhack\Projects\google_brain\Climate_data\INMET_CO_DF_A001_BRASILIA_01-01-2020_A_31-12-2020.csv",
                                skiprows=8,
                                sep=";",         
                                encoding="latin1")

climate_data_2020.head()

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
0,2020/01/01,0000 UTC,0,"884,1","884,2","883,9",NaN,20,"18,1","20,2","19,6","18,4","17,7",89,88.0,89,108,"2,7",",8",NaN
1,2020/01/01,0100 UTC,0,885,885,"884,1",NaN,"19,5","18,1",20,"19,4","18,4","17,8",91,89.0,91,272,"1,4",",3",NaN
2,2020/01/01,0200 UTC,0,"885,5","885,5",885,NaN,20,"18,8","20,1","19,4","18,9","18,1",94,91.0,93,40,"1,5","1,1",NaN
3,2020/01/01,0300 UTC,0,"885,3","885,5","885,3",NaN,"19,5","17,9","20,2","19,4",19,"17,8",93,90.0,91,319,"2,6",1,NaN
4,2020/01/01,0400 UTC,0,"885,2","885,4","885,2",NaN,"19,5","17,3","19,8","19,3","18,2","17,3",92,87.0,87,321,"2,7","1,4",NaN

In [15]:
climate_data_2020['Data'] = pd.to_datetime(climate_data_2020['Data'], format="%Y/%m/%d", errors='coerce')

for col in climate_data_2020.columns[2:]: #starting on the third column
    climate_data_2020[col] = (
        climate_data_2020[col].astype(str)
        .str.replace(",", ".")
        .str.strip()
        .replace("", "0")
        .astype(float)
    )

meteo_daily_2020 = climate_data_2020.groupby('Data').agg({
    'PRECIPITAÇÃO TOTAL, HORÁRIO (mm)': 'sum',
    'RADIACAO GLOBAL (Kj/m²)': 'mean',
    'TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)': 'mean',
    'TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)': 'max',
    'TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)': 'min',
    'TEMPERATURA DO PONTO DE ORVALHO (°C)': 'mean',
    'UMIDADE RELATIVA DO AR, HORARIA (%)': 'mean',
    'VENTO, RAJADA MAXIMA (m/s)': 'max',
    'VENTO, VELOCIDADE HORARIA (m/s)': 'mean'
}).reset_index()


meteo_daily_2020.rename(columns={
    'PRECIPITAÇÃO TOTAL, HORÁRIO (mm)': 'precipitacao_mm',
    'RADIACAO GLOBAL (Kj/m²)': 'radiacao_media',
    'TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)': 'temp_media',
    'TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)': 'temp_max',
    'TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)': 'temp_min',
    'TEMPERATURA DO PONTO DE ORVALHO (°C)': 'temp_orvalho_media',
    'UMIDADE RELATIVA DO AR, HORARIA (%)': 'humidade_media',
    'VENTO, RAJADA MAXIMA (m/s)': 'vento_rajada_max',
    'VENTO, VELOCIDADE HORARIA (m/s)': 'vento_vel_media'
}, inplace=True)

meteo_daily_2020.head()

,Data,precipitacao_mm,radiacao_media,temp_media,temp_max,temp_min,temp_orvalho_media,humidade_media,vento_rajada_max,vento_vel_media
0,2020-01-01,0.4,944.492857,21.162500,25.2,18.7,17.654167,80.958333,8.9,1.516667
1,2020-01-02,0.0,1350.621429,21.879167,27.1,19.1,18.087500,80.000000,8.0,2.783333
2,2020-01-03,31.4,1382.633333,21.395833,27.6,18.3,18.054167,82.541667,10.8,2.625000
3,2020-01-04,19.6,931.114286,20.300000,25.2,18.8,18.462500,89.500000,13.0,3.437500
4,2020-01-05,57.4,425.686667,19.120833,23.0,17.4,18.037500,93.416667,9.0,2.133333

In [16]:
climate_data_2019 = pd.read_csv(r"C:\Users\sofia\Documents\Data_Analytics_Ironhack\Projects\google_brain\Climate_data\INMET_CO_DF_A001_BRASILIA_01-01-2019_A_31-12-2019.csv",
                                skiprows=8,
                                sep=";",         
                                encoding="latin1")

climate_data_2019.head()

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (KJ/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
0,2019/01/01,0000 UTC,1,887,887,"886,6",NaN,"18,5",17,"18,7","18,4","17,3","16,9",92.0,91.0,91.0,330.0,"5,3",2,NaN
1,2019/01/01,0100 UTC,0,"888,1","888,1",887,NaN,"18,4","17,1","18,5","18,3","17,2","16,9",92.0,91.0,92.0,326.0,"4,3",",8",NaN
2,2019/01/01,0200 UTC,0,"888,2","888,3","888,1",NaN,"18,5","17,3","18,6","18,3","17,4","17,1",93.0,92.0,93.0,340.0,"2,2","1,3",NaN
3,2019/01/01,0300 UTC,",4","887,6","888,2","887,6",NaN,"18,4","17,1","18,7","18,4","17,5","17,1",93.0,92.0,92.0,351.0,"2,2","1,4",NaN
4,2019/01/01,0400 UTC,0,887,"887,6",887,NaN,"17,9","16,7","18,4","17,9","17,2","16,7",93.0,92.0,93.0,343.0,2,"1,3",NaN

In [17]:
climate_data_2019['Data'] = pd.to_datetime(climate_data_2019['Data'], format="%Y/%m/%d", errors='coerce')

for col in climate_data_2019.columns[2:]: #starting on the third column
    climate_data_2019[col] = (
        climate_data_2019[col].astype(str)
        .str.replace(",", ".")
        .str.strip()
        .replace("", "0")
        .astype(float)
    )

meteo_daily_2019 = climate_data_2019.groupby('Data').agg({
    'PRECIPITAÇÃO TOTAL, HORÁRIO (mm)': 'sum',
    'RADIACAO GLOBAL (KJ/m²)': 'mean',
    'TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)': 'mean',
    'TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)': 'max',
    'TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)': 'min',
    'TEMPERATURA DO PONTO DE ORVALHO (°C)': 'mean',
    'UMIDADE RELATIVA DO AR, HORARIA (%)': 'mean',
    'VENTO, RAJADA MAXIMA (m/s)': 'max',
    'VENTO, VELOCIDADE HORARIA (m/s)': 'mean'
}).reset_index()


meteo_daily_2019.rename(columns={
    'PRECIPITAÇÃO TOTAL, HORÁRIO (mm)': 'precipitacao_mm',
    'RADIACAO GLOBAL (KJ/m²)': 'radiacao_media',
    'TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)': 'temp_media',
    'TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)': 'temp_max',
    'TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)': 'temp_min',
    'TEMPERATURA DO PONTO DE ORVALHO (°C)': 'temp_orvalho_media',
    'UMIDADE RELATIVA DO AR, HORARIA (%)': 'humidade_media',
    'VENTO, RAJADA MAXIMA (m/s)': 'vento_rajada_max',
    'VENTO, VELOCIDADE HORARIA (m/s)': 'vento_vel_media'
}, inplace=True)

meteo_daily_2019.head()

,Data,precipitacao_mm,radiacao_media,temp_media,temp_max,temp_min,temp_orvalho_media,humidade_media,vento_rajada_max,vento_vel_media
0,2019-01-01,1.4,1192.792308,20.520833,26.2,17.8,17.225000,82.208333,6.7,1.591667
1,2019-01-02,0.0,2300.976923,22.716667,29.2,16.9,16.583333,71.041667,8.3,2.070833
2,2019-01-03,0.0,2053.046154,24.341667,29.6,17.5,14.283333,56.208333,7.0,2.108333
3,2019-01-04,0.0,1704.600000,23.425000,28.9,18.7,14.979167,61.375000,7.9,1.833333
4,2019-01-05,1.0,886.907692,20.866667,26.1,17.7,16.600000,77.250000,12.0,1.250000

In [18]:
climate_data_2018 = pd.read_csv(r"C:\Users\sofia\Documents\Data_Analytics_Ironhack\Projects\google_brain\Climate_data\INMET_CO_DF_A001_BRASILIA_01-01-2018_A_31-12-2018.csv",
                                skiprows=8,
                                sep=";",         
                                encoding="latin1",
                                dtype={'DATA (YYYY-MM-DD)': str}
                                )

climate_data_2018.head()

,DATA (YYYY-MM-DD),HORA (UTC),"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (KJ/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
0,2018-01-01,00:00,0,"887,8","887,8","887,1",-9999,"21,8",18,"21,8","21,6","18,2","17,7",81,78,79,117,4,"1,6",NaN
1,2018-01-01,01:00,0,"888,2","888,3","887,8",-9999,"21,8","17,9","21,9","21,5","18,5","17,9",83,78,79,135,"2,8","1,3",NaN
2,2018-01-01,02:00,0,"888,5","888,5","888,2",-9999,"20,8","17,8","21,8","20,8","18,1","17,7",83,78,83,131,"2,1",",4",NaN
3,2018-01-01,03:00,0,"888,1","888,6","888,1",-9999,"21,2","17,9","21,3","20,5","18,2","17,8",85,81,81,120,"2,8","1,5",NaN
4,2018-01-01,04:00,0,"887,4","888,1","887,4",-9999,"20,9","17,4","21,2","20,7","18,2","17,4",84,81,81,133,"2,8","1,2",NaN

In [19]:
climate_data_2018['DATA (YYYY-MM-DD)'] = climate_data_2018['DATA (YYYY-MM-DD)'].str.strip()

climate_data_2018['DATA (YYYY-MM-DD)'] = pd.to_datetime(climate_data_2018['DATA (YYYY-MM-DD)'], format="%Y-%m-%d", errors='coerce')

print(climate_data_2018['DATA (YYYY-MM-DD)'].head(), climate_data_2018['DATA (YYYY-MM-DD)'].isna().sum())

0   2018-01-01
1   2018-01-01
2   2018-01-01
3   2018-01-01
4   2018-01-01
Name: DATA (YYYY-MM-DD), dtype: datetime64[ns] 0

In [25]:
import numpy as np

climate_data_2018.rename(columns={"DATA (YYYY-MM-DD)": "Data"}, inplace=True)

for col in climate_data_2018.columns:
    if col != "Data":
        climate_data_2018[col] = (
            climate_data_2018[col].astype(str)
            .str.replace(",", ".", regex=False)
            .replace("-9999", np.nan)
            .replace("", np.nan)
        )
        climate_data_2018[col] = pd.to_numeric(climate_data_2018[col], errors="coerce")


for col in climate_data_2018.columns:
    if col != "Data" and climate_data_2018[col].dtype == object:
        climate_data_2018[col] = (
            climate_data_2018[col].astype(str)
            .str.replace(",", ".")
            .str.strip()
            .replace("-9999", np.nan)
            .replace("", np.nan)
        )
        climate_data_2018[col] = pd.to_numeric(climate_data_2018[col], errors="coerce")

# 5. Agregar por dia
meteo_daily_2018 = climate_data_2018.groupby("Data").agg({
    "PRECIPITAÇÃO TOTAL, HORÁRIO (mm)": "sum",
    "RADIACAO GLOBAL (KJ/m²)": "mean",
    "TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)": "mean",
    "TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)": "max",
    "TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)": "min",
    "TEMPERATURA DO PONTO DE ORVALHO (°C)": "mean",
    "UMIDADE RELATIVA DO AR, HORARIA (%)": "mean",
    "VENTO, RAJADA MAXIMA (m/s)": "max",
    "VENTO, VELOCIDADE HORARIA (m/s)": "mean"
}).reset_index()

# 6. Renomear colunas
meteo_daily_2018.rename(columns={
    "PRECIPITAÇÃO TOTAL, HORÁRIO (mm)": "precipitacao_mm",
    "RADIACAO GLOBAL (KJ/m²)": "radiacao_media",
    "TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)": "temp_media",
    "TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)": "temp_max",
    "TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)": "temp_min",
    "TEMPERATURA DO PONTO DE ORVALHO (°C)": "temp_orvalho_media",
    "UMIDADE RELATIVA DO AR, HORARIA (%)": "humidade_media",
    "VENTO, RAJADA MAXIMA (m/s)": "vento_rajada_max",
    "VENTO, VELOCIDADE HORARIA (m/s)": "vento_vel_media"
}, inplace=True)

meteo_daily_2018.head()

,Data,precipitacao_mm,radiacao_media,temp_media,temp_max,temp_min,temp_orvalho_media,humidade_media,vento_rajada_max,vento_vel_media
0,2018-01-01,16.2,849.384615,21.570833,26.3,19.4,18.225000,81.833333,6.4,1.429167
1,2018-01-02,0.6,1566.622222,21.066667,27.3,17.9,17.477778,81.500000,8.0,1.627778
2,2018-01-03,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2018-01-04,0.0,764.833333,24.842857,27.2,22.2,16.342857,60.000000,7.8,2.766667
4,2018-01-05,11.4,590.400000,20.179167,23.9,18.1,17.558333,85.291667,8.2,1.762500

In [26]:
meteo_daily_2024.columns

Index(['Data', 'precipitacao_mm', 'radiacao_media', 'temp_media', 'temp_max',
       'temp_min', 'temp_orvalho_media', 'humidade_media', 'vento_rajada_max',
       'vento_vel_media'],
      dtype='object')

In [27]:
print(meteo_daily_2023.columns)
print(meteo_daily_2022.columns)
print(meteo_daily_2021.columns)
print(meteo_daily_2020.columns)
print(meteo_daily_2019.columns)
print(meteo_daily_2018.columns)

Index(['Data', 'precipitacao_mm', 'radiacao_media', 'temp_media', 'temp_max',
       'temp_min', 'temp_orvalho_media', 'humidade_media', 'vento_rajada_max',
       'vento_vel_media'],
      dtype='object')
Index(['Data', 'precipitacao_mm', 'radiacao_media', 'temp_media', 'temp_max',
       'temp_min', 'temp_orvalho_media', 'humidade_media', 'vento_rajada_max',
       'vento_vel_media'],
      dtype='object')
Index(['Data', 'precipitacao_mm', 'radiacao_media', 'temp_media', 'temp_max',
       'temp_min', 'temp_orvalho_media', 'humidade_media', 'vento_rajada_max',
       'vento_vel_media'],
      dtype='object')
Index(['Data', 'precipitacao_mm', 'radiacao_media', 'temp_media', 'temp_max',
       'temp_min', 'temp_orvalho_media', 'humidade_media', 'vento_rajada_max',
       'vento_vel_media'],
      dtype='object')
Index(['Data', 'precipitacao_mm', 'radiacao_media', 'temp_media', 'temp_max',
       'temp_min', 'temp_orvalho_media', 'humidade_media', 'vento_rajada_max',
       'vento_vel_media'],
      dtype='object')
Index(['Data', 'precipitacao_mm', 'radiacao_media', 'temp_media', 'temp_max',
       'temp_min', 'temp_orvalho_media', 'humidade_media', 'vento_rajada_max',
       'vento_vel_media'],
      dtype='object')

In [29]:
merged_meteo = pd.concat([
    meteo_daily_2024,meteo_daily_2023,
    meteo_daily_2022,meteo_daily_2021,meteo_daily_2020, meteo_daily_2019,
    meteo_daily_2018], ignore_index=True)

merged_meteo.head()

,Data,precipitacao_mm,radiacao_media,temp_media,temp_max,temp_min,temp_orvalho_media,humidade_media,vento_rajada_max,vento_vel_media
0,2024-01-01,35.6,1094.385714,21.995833,26.7,19.4,18.666667,82.541667,6.2,1.658333
1,2024-01-02,23.2,1171.950000,21.187500,26.6,19.3,19.570833,91.000000,6.7,1.787500
2,2024-01-03,48.8,724.321429,20.537500,23.4,19.1,19.370833,93.375000,8.2,2.250000
3,2024-01-04,7.6,590.893333,20.375000,23.3,19.3,19.491667,94.750000,8.4,2.529167
4,2024-01-05,2.4,833.607143,20.400000,23.2,18.9,19.004167,92.125000,11.1,2.545833

In [30]:
merged_meteo.shape

(2557, 10)

In [31]:
merged_meteo.isna().sum()

Data                  0
precipitacao_mm       0
radiacao_media        1
temp_media            1
temp_max              1
temp_min              1
temp_orvalho_media    1
humidade_media        1
vento_rajada_max      1
vento_vel_media       1
dtype: int64

In [32]:
merged_meteo.to_csv(r"C:\Users\sofia\Documents\Data_Analytics_Ironhack\Projects\google_brain\Climate_data\merged_meteo.csv", index=False)